config/routes.rb
FirstApp::Application.routes.draw do
  resources :badges
  resources :seeks
  resources :users
  
  root :to => "application#index", via: 'get'
  match 'auth/:provider/callback', to: 'sessions#create' , via: 'get'
  match 'auth/failure', to: redirect('/') , via: 'get'
  match 'signout', to: 'sessions#destroy', as: 'signout' , via: 'get'

  match 'seeks/:id/join', to: 'seeks#join', via: 'get'
  match 'seeks/:id/close', to: 'seeks#close', via: 'get'
  match 'seeks/:id/donate', to: 'seeks#donate', via: 'get'
  match 'home', to: 'application#home', via: 'get'
  match 'profile_edit' , to: 'application#edit', via: 'get'

end

app/models/seek.rb
class Seek < ActiveRecord::Base
	has_and_belongs_to_many :users
	  geocoded_by :address
	  after_validation :geocode, :if => :address_changed?
end

app/controllers/seeks_controller.rb
class SeeksController < ApplicationController
  # GET /seeks
  # GET /seeks.json
  def index
    @seeks = Seek.all
  end

  def donate
    s = Seek.find_by_id(params[:id])
    s.users.append(current_user)
    current_user.points += 100
    current_user.redeemable += 100
    current_user.save
    #redirect_to "/",notice: 'You just got more cash'
  end
  # GET /seeks/1
  # GET /seeks/1.json
  def show
    @seek = Seek.find(params[:id])
    @supporters = @seek.users
  end

  # GET /seeks/new
  def new
    @seek = Seek.new
  end

  # GET /seeks/1/edit
  def edit
  end

  # POST /seeks
  # POST /seeks.json
  def create
    #uset = current user's id
    @seek = Seek.new(seek_params)
    current_user.points += 20
    current_user.redeemable += 20
    current_user.save
    respond_to do |format|
      if @seek.save
        format.html { redirect_to @seek, notice: 'Seek was successfully created.' }
        format.json { render action: 'show', status: :created, location: @seek }
      else
        format.html { render action: 'new' }
        format.json { render json: @seek.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seeks/1
  # PATCH/PUT /seeks/1.json
  def update
    respond_to do |format|
      if @seek.update(seek_params)
        format.html { redirect_to @seek, notice: 'Seek was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @seek.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seeks/1
  # DELETE /seeks/1.json
  def destroy
    @seek.destroy
    respond_to do |format|
      format.html { redirect_to seeks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seek
      @seek = Seek.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seek_params
      params.require(:seek).permit(:user_id, :patient_name, :contact_number, :address, :medical_issue, :latitude, :longitude, :city, :state, :country, :hospital, :hospital_address, :pincode)
    end
  
end

app/helpers/seeks_helper.rb
module SeeksHelper
end

app/views/seeks/_form.html.erb
<%= form_for(@seek) do |f| %>
  <% if @seek.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seek.errors.count, "error") %> prohibited this seek from being saved:</h2>

      <ul>
      <% @seek.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :patient_name %><br>
    <%= f.text_field :patient_name %>
  </div>
  <div class="field">
    <%= f.label :contact_number %><br>
    <%= f.number_field :contact_number %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :medical_issue %><br>
    <%= f.text_field :medical_issue %>
  </div>
  <div class="field">
    <%= f.label "Blood Group" %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :hospital %><br>
    <%= f.text_field :hospital %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seeks/donate.js.erb
console.log("asdf");
$("#don").fadeOut('slow').load('<%= params[:id] %> #don').fadeIn("slow");
	

app/views/seeks/edit.html.erb
<h1>Editing seek</h1>

<%= render 'form' %>

<%= link_to 'Show', @seek %> |
<%= link_to 'Back', seeks_path %>

app/views/seeks/index.html.erb
<h1>Listing seeks</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Patient name</th>
      <th>Contact number</th>
      <th>Address</th>
      <th>Medical issue</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Hospital</th>
      <th>Hospital address</th>
      <th>Pincode</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @seeks.each do |seek| %>
      <tr>
        <td><%= seek.user_id %></td>
        <td><%= seek.patient_name %></td>
        <td><%= seek.contact_number %></td>
        <td><%= seek.address %></td>
        <td><%= seek.medical_issue %></td>
        <td><%= seek.latitude %></td>
        <td><%= seek.longitude %></td>
        <td><%= seek.city %></td>
        <td><%= seek.state %></td>
        <td><%= seek.country %></td>
        <td><%= seek.hospital %></td>
        <td><%= seek.hospital_address %></td>
        <td><%= seek.pincode %></td>
        <td><%= link_to 'Show', seek %></td>
        <td><%= link_to 'Edit', edit_seek_path(seek) %></td>
        <td><%= link_to 'Destroy', seek, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seek', new_seek_path %>

app/views/seeks/new.html.erb
<%# render 'form' %>

<%# link_to 'Back', seeks_path %>

        <%= render 'layouts/navbar' %>


      <h2>New Blood Seek</h2>  
      <hr>
<%= render 'form' %> 


  <script src="../assets/js/jquery-1.10.2.min.js"></script>
  <script src="../assets/js/bootstrap.min.js"></script>


</body>


</html>

app/views/seeks/show.html.erb
        
<!DOCTYPE html>
<html lang="en">
    <head>
              <script type="text/javascript" src="../assets/custom.js"></script>

        <title>Fun with Google Maps | Sickdesigner.com</title>
        <meta charset="utf-8">
        <meta name="description" content="Demo page for http://sickdesigner.com/fun-with-google-maps">
        <link rel="stylesheet" href="http://sickdesigner.com/demo/fun-with-google-maps/css/reset.css" type="text/css" media="screen">
        <link rel="stylesheet" href="../assets/style.css" type="text/css" media="screen">       
      <link href='http://fonts.googleapis.com/css?family=Life+Savers' rel='stylesheet' type='text/css'> 
        <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>   
            
        <script type="text/javascript" src="js/html5.js"></script>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>     
    
        <script type="text/javascript"
          src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDl5CEPqEKUgpi3FLY6evlhgedJReK62GE&amp;sensor=true">
        </script>
        <script type="text/javascript">
      function initialize() {
        var mapOptions = {
          center: new google.maps.LatLng(<%= @seek.latitude %> , <%= @seek.longitude %>),
          zoom: 12,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("gmap"),
            mapOptions);
  
  var contentString = '<font color="black"><div id="content">'+'<p>Name : <%= @seek.patient_name %>  </p>'+'<p>Address : <%= @seek.address %>  </p>'+'<p>Contact : <%= @seek.contact_number %>  </p>'
      '</font>';
            
  //newmarker(28.5060459, 77.2714055,"magus",contentString);newmarker(28.5460459, 77.2714055,"magus",contentString);//,'image2.png'); 
  
  newmarker(<%= @seek.latitude %> , <%= @seek.longitude %>,"Magus",contentString);
  <% User.all.each do |u| %>
  <% if !u.distance_from(@seek).nil? %>
  <%= "newmarker(" + u.latitude.to_s + "," + u.longitude.to_s  %>,"<font color='black'><p>donor : <%= u.name %> </p></font>","<font color='black'> <p>Donor : <%= u.name %></p><p>Contact : <%= u.phone %></p></font>");
  <% end %>
 <% end %>
 /* function toggleBounce() {
    newmarker(28.5460454, 77.2710000,this.text);
  }*/
  
  function newmarker(x,y,text,contentString){
    var myLatlng = new google.maps.LatLng(x, y);
          var marker = new google.maps.Marker({
        position: myLatlng,
        map: map,
        draggable:false,
       // animation: google.maps.Animation.DROP,
    //position: parliament,
     title:text
    });
      var infowindow = new google.maps.InfoWindow({
            content: contentString
        });

       google.maps.event.addListener(marker, 'click', function() {
          infowindow.open(map,marker);
        });
    marker.setMap(map);
  }
  /*function newmarker(x,y,text,urll){
    //  var image = 'leaflet/image2.png';
    var image = {
          url: urll,
          size: new google.maps.Size(20, 32),
          origin: new google.maps.Point(0,0),
          anchor: new google.maps.Point(0, 32)
        };
    var myLatlng = new google.maps.LatLng(x, y);
          var marker = new google.maps.Marker({
        position: myLatlng,
        map: map,
        title:text,
    icon: image
    });
    marker.setMap(map);
  }*/
  /*var myLatlng = new google.maps.LatLng(28.5460459, 77.2714055);
        var marker = new google.maps.Marker({
      position: myLatlng,
      map: map,
      title:"magus"});*/
  }
  
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
    <script type="text/javascript">

          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-31695326-1']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();


        </script>
            </head>
    <body onload="initialize()">
        <div id="gmap"></div>
        <div id="container">
            <span class="number">+</span>
            <span class="switch">ON</span>
            <hgroup>
              <h1> Donate Blood Request  </h1>
               <h2> Blood Group <%= @seek.country %>  </h2></br>
                <h2>Patient name: <%= @seek.patient_name %></h2>
            </hgroup>  
            <p>

<p>
  <strong> Contact number:  </strong>
  <%= @seek.contact_number %>
</p>

<p>
  <strong>Address:</strong>
  <%= @seek.address %>
</p>

<p>
  <strong>Medical issue:</strong>
  <%= @seek.medical_issue %>
</p>


<p>
  <strong>Hospital:</strong>
  <%= @seek.hospital %>
</p>
<p id="don">
  <strong>Donators:</strong>
  <% @supporters.each do |s| %>
  <%=  link_to s.name, user_path(s) %>
  <% end %>
</p>

                <br>
                
              <nav>
               <script>
               $("#last").click(function() {
  alert( "Handler for .click() called." );
  $("#don").fadeOut('slow').load('seeks/<%= params[:id] %> #don').fadeIn("slow");
});
               </script>
                <a href="<%= params[:id] %>/donate" class="last" id="last" data-remote="true">Donate Blood</a>
            </nav>
        </div>        
    </body>
</html>