config/routes.rb
FirstApp::Application.routes.draw do
  resources :badges
  resources :seeks
  resources :users
  
  root :to => "application#index", via: 'get'
  match 'auth/:provider/callback', to: 'sessions#create' , via: 'get'
  match 'auth/failure', to: redirect('/') , via: 'get'
  match 'signout', to: 'sessions#destroy', as: 'signout' , via: 'get'

  match 'seeks/:id/join', to: 'seeks#join', via: 'get'
  match 'seeks/:id/close', to: 'seeks#close', via: 'get'
  match 'seeks/:id/donate', to: 'seeks#donate', via: 'get'
  match 'home', to: 'application#home', via: 'get'
  match 'profile_edit' , to: 'application#edit', via: 'get'

end

app/models/badge.rb
class Badge < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :set_badge, only: [:show, :edit, :update, :destroy]

  # GET /badges
  # GET /badges.json
  def index
    @badges = Badge.all
  end

  # GET /badges/1
  # GET /badges/1.json
  def show
  end

  # GET /badges/new
  def new
    @badge = Badge.new
  end

  # GET /badges/1/edit
  def edit
  end

  # POST /badges
  # POST /badges.json
  def create
    @badge = Badge.new(badge_params)

    respond_to do |format|
      if @badge.save
        format.html { redirect_to @badge, notice: 'Badge was successfully created.' }
        format.json { render action: 'show', status: :created, location: @badge }
      else
        format.html { render action: 'new' }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /badges/1
  # PATCH/PUT /badges/1.json
  def update
    respond_to do |format|
      if @badge.update(badge_params)
        format.html { redirect_to @badge, notice: 'Badge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @badge.destroy
    respond_to do |format|
      format.html { redirect_to badges_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_badge
      @badge = Badge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def badge_params
      params.require(:badge).permit(:image_link, :name, :value)
    end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/badges/_form.html.erb
<%= form_for(@badge) do |f| %>
  <% if @badge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@badge.errors.count, "error") %> prohibited this badge from being saved:</h2>

      <ul>
      <% @badge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_link %><br>
    <%= f.text_field :image_link %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.number_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/badges/edit.html.erb
<h1>Editing badge</h1>

<%= render 'form' %>

<%= link_to 'Show', @badge %> |
<%= link_to 'Back', badges_path %>

app/views/badges/index.html.erb
<h1>Listing badges</h1>

<table>
  <thead>
    <tr>
      <th>Image link</th>
      <th>Name</th>
      <th>Value</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @badges.each do |badge| %>
      <tr>
        <td><%= badge.image_link %></td>
        <td><%= badge.name %></td>
        <td><%= badge.value %></td>
        <td><%= link_to 'Show', badge %></td>
        <td><%= link_to 'Edit', edit_badge_path(badge) %></td>
        <td><%= link_to 'Destroy', badge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Badge', new_badge_path %>

app/views/badges/new.html.erb
<h1>New badge</h1>

<%= render 'form' %>

<%= link_to 'Back', badges_path %>

app/views/badges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image link:</strong>
  <%= @badge.image_link %>
</p>

<p>
  <strong>Name:</strong>
  <%= @badge.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @badge.value %>
</p>

<%= link_to 'Edit', edit_badge_path(@badge) %> |
<%= link_to 'Back', badges_path %>