config/routes.rb
FirstApp::Application.routes.draw do
  resources :badges
  resources :seeks
  resources :users
  
  root :to => "application#index", via: 'get'
  match 'auth/:provider/callback', to: 'sessions#create' , via: 'get'
  match 'auth/failure', to: redirect('/') , via: 'get'
  match 'signout', to: 'sessions#destroy', as: 'signout' , via: 'get'

  match 'seeks/:id/join', to: 'seeks#join', via: 'get'
  match 'seeks/:id/close', to: 'seeks#close', via: 'get'
  match 'seeks/:id/donate', to: 'seeks#donate', via: 'get'
  match 'home', to: 'application#home', via: 'get'
  match 'profile_edit' , to: 'application#edit', via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_and_belongs_to_many :seeks
	has_and_belongs_to_many :badges
	#validates :email, presence: true
	geocoded_by :address
	  after_validation :geocode, :if => :address_changed?
	def self.from_omniauth(auth)
	  where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
	    user.provider = auth.provider
	    user.uid = auth.uid
	    user.name = auth.info.name
	    user.points = 10 if user.points.nil?
	    user.redeemable = 10 if user.redeemable.nil?
	    #user.email = auth.extra.user_hash.email
	    user.oauth_token = auth.credentials.token
	    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
	    user.save!
	  end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if current_user.points > 100
      id = Badge.first.id
      flag = false
      current_user.badges.all do |b|
          flag = true if b.id == id
      end
      current_user.badges.delete_all
         current_user.badges.append(Badge.first) if flag == false
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :bg, :phone, :address)
    end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="col-md-4">
  <div class="box">
<form class="form-horizontal" role="form" >

  <div class="form-group">
    <%= f.label :email ,class: 'col-sm-2 control-label'%>
    </div>
    <div class="col-sm-10">
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group ,class: 'col-sm-2 control-label'">
    <%= f.label :bg %><br>
    <%= f.text_field :bg, class: "form-control"  %>
  </div>
  <div class="form-group",class: 'col-sm-2 control-label>
    <%= f.label :phone %><br>
    <%= f.number_field :phone, class: "form-control"  %>
  </div>
  <div class="form-group",class: 'col-sm-2 control-label>
    <%= f.label :address %><br>
    <%= f.text_field :address , class: "form-control" %>
  </div>
  <div class="form-group",class: 'col-sm-2 control-label>
    <%= f.submit %>

  </div>
</form>
</div>
</div>
<% end %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script src="../assets/js/bootstrap.min.js"></script>

app/views/users/edit.html.erb
 <%= render 'layouts/navbar' %>
<h1>Editing user</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Bg</th>
      <th>Phone</th>
      <th>Address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.bg %></td>
        <td><%= user.phone %></td>
        <td><%= user.address %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">

<link rel='stylesheet' id='sharedaddy-css'  href='../assets/css/bootstrap.css' type='text/css' media='all' />
<link rel='stylesheet' id='sharedaddy-css'  href='../assets/css/main.css' type='text/css' media='all' />
<link rel='stylesheet' id='sharedaddy-css'  href='../assets/css/font-awesome.css' type='text/css' media='all' />
<link rel='stylesheet' id='sharedaddy-css'  href='../assets/css/font-awesome.min.css' type='text/css' media='all' />

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><b><span class="glyphicon glyphicon-plus"></span>BloodSeeker</b></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">

			      <li class="dropdown">
			        <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account<b class="caret"></b></a>
			        <ul class="dropdown-menu">
                <li><%= link_to 'Edit Profile',  edit_user_path(current_user) %></li>

			          <li class="divider"></li>
                                <li>    <%= link_to "Sign out", signout_path, id: "sign_out" %>  </li>

			        </ul>
			      </li>
          </ul>
        </div>
      </div>
    </div>

<h1>New user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../assets/img/favicon.png">
    
    <link rel="stylesheet" href="../assets/css/font-awesome.min.css">


    <title>User Account</title>

    <!-- Bootstrap core CSS -->
    <link href="../assets/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="../assets/css/main.css" rel="stylesheet">

    <!-- Fonts from Google Fonts -->
	<link href='http://fonts.googleapis.com/css?family=Lato:300,400,900' rel='stylesheet' type='text/css'>
    
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Fixed navbar -->
    <%= render 'layouts/navbar' %>
<p id="notice"><%= notice %></p>
    
    <div class="row" >
    	<div class="col-md-8">
    		<div class="box" style="padding-left:40px; height:250px" >
    			<div class="container-fluid">
    				<div class="row-fluid">
	    				<div class="col-md-4"> 
<a href="http://facebook.com/<%= @user.uid %>">	<img class="img-thumbnail" src="http://graph.facebook.com/<%= @user.uid %>/picture?width=140&height=150" alt=""> </a>
	    				</div>
	    				<div class="col-md-4" height="800px"> 
	    					<h2><%= @user.name %></h2>
	    					<h4>BLOOD TYPE : <%= @user.bg %></h4>
	    					<h4>Contact : <%= @user.phone %></h4>
	    					<h4>Location :<%= @user.address %></h4>
	    	</div>
	    				<div class="col-md-4" style="height:-20px;"> 
	    					

	    				</div>

    				</div>
    			</div>
    		</div>
    	</div>

    
    		<div class="col-md-4">
    			<div class="box" style="height:800px">
    						

    				 <div class="well">
                    
                            <h2>BADGES</h2>
                            <% @user.badges.each do |b| %>
                              <img class="img-thumbnail" src="<%= b.image_link %>" alt="">
	    					          <a href="#"><h4><%= b.name %></h4></a>
                          <% end %>
	    					         
                    
                	</div>	
                	 <div class="well">
                            <h2>Your Points: <b><%= @user.points %></b></h2>
	    				    </div>	
                <div class="well">
                            <h2>Available for Redeem: <b><%= @user.redeemable %></b></h2>
                  </div>  
    			</div>
    		</div>
    </div>

    <div class="row">
    	<div class="col-md-8">
    		<div class="box" style="margin-top:-500px">
    			<div class="well">
                    
                        <table class="table">
                              <thead>
                              <tr>
                                
                                <th>Blood Donate History</th>
                                
                              </tr>
                                </thead>
                            
                             <tbody>
                                                              <% @user.seeks.each do |s| %>

                              <tr>
                                <td>    <%= link_to "To "+s.patient_name.to_s+" on "+s.updated_at.to_s, seek_path(s) %></td> 
                              </tr>
                                                              <% end %>

                                 </tbody>
                        </table>    
                        <table class="table">
                              <thead>
                              <tr>
                                
                                <th>Blood Seek History</th>
                                
                              </tr>
                                </thead>
                            
                             <tbody>
                                <% t = Seek.where(user_id:current_user.id) %>
                                <% t.each do |s| %>
                              <tr>
                                <td>    <%= link_to s.updated_at, seek_path(s) %></td> 
                              </tr>
                                <% end %>
                                 </tbody>
                        </table>    
            	</div>
    		</div>
    	</div>
    </div>

    

	
	
	
	
	
	
	

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="../assets/js/bootstrap.min.js"></script>
  </body>
</html>