config/routes.rb
FirstApp::Application.routes.draw do
  resources :badges
  resources :seeks
  resources :users
  
  root :to => "application#index", via: 'get'
  match 'auth/:provider/callback', to: 'sessions#create' , via: 'get'
  match 'auth/failure', to: redirect('/') , via: 'get'
  match 'signout', to: 'sessions#destroy', as: 'signout' , via: 'get'

  match 'seeks/:id/join', to: 'seeks#join', via: 'get'
  match 'seeks/:id/close', to: 'seeks#close', via: 'get'
  match 'seeks/:id/donate', to: 'seeks#donate', via: 'get'
  match 'home', to: 'application#home', via: 'get'
  match 'profile_edit' , to: 'application#edit', via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  def index
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
    redirect_to home_path, notice: 'Succesfully logged in' unless @current_user.nil?
  end

  def home
    
  end

  def edit
    edit_user_path(current_user)
  end

  protect_from_forgery with: :exception
	private

	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
helper_method :current_user
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="assets/img/favicon.png">
    
    <link rel="stylesheet" href="assets/css/font-awesome.min.css">


    <title>Home</title>

    <!-- Bootstrap core CSS -->
    <link href="assets/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="assets/css/main.css" rel="stylesheet">

    <!-- Fonts from Google Fonts -->
	<link href='http://fonts.googleapis.com/css?family=Lato:300,400,900' rel='stylesheet' type='text/css'>
    
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->


  </head>

  <body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

    <!-- Fixed navbar -->
        <%= render 'layouts/navbar' %>


    <div class="row">
    	<div class="col-md-8">
    		<div class="box" style="padding-left:40px;height:150px;">
    			<div class="container-fluid">
    				<a  href="/seeks/new"><button type="button" class="btn btn-danger btn-lg btn-block">Find Blood</button></a>
            <center><h4>Search for donor's around you.</h4></center>
    			</div>
    		</div>
    	</div>

    
    		<div class="col-md-4">
    			<div class="box" style="height:800px">
    						

    				 <div class="well">
                    
                            <h2>Leaderboard</h2>
	    				<table class="table table-hover">
                            
                            <tbody>
                              <th>#</th>
                              <th></th>
                              <th>Points</th>
                              <% User.all.order(points: :desc).each_with_index do |u,i|%>
                                <tr>
                                <td><%= i+1 %></td>
                                <td><%= link_to u.name,  user_path(u) %></td>
                                <td><%= u.points %></td>
                                </tr>
                                <% end %>
                              
                            </tbody>
                          </table>         
                    
                	</div>	
                	
    			</div>
    		</div>
    </div>

    <div class="row">
    	<div class="col-md-8">
    		<div class="box" style="margin-top:-600px;height:1000px">
        <h2>SEEKERS</h2>

                <ol class="breadcrumb">
                Sort by :    
                  <li><a href="?time=true">Time</a></li>
                  <li><a href="?dist=true">Distance</a></li>
                  <li class="active"></li>
                </ol>

<hr>

<%# debug(params) %>
<% if params[:dist] == 'true' %>
                             

<% else %>
 <% Seek.all.order(created_at: :desc).each do |s|%>

          <div class="well">
              <li class="active">
               <a href="/seeks/<%= s.id %>"><%= s.patient_name %></a>
                 <a href="https://www.facebook.com/sharer/sharer.php?u=<%= seek_url(s)%>" %> <button type="button" class="btn btn-default btn-xs pull-right" style="margin-left:70px;"><i class="fa fa-facebook"></i>Share</button> </a>
                 <span class="label label-danger pull-right" style="margin:5px;"><%= s.country %></span>
                 <span class="label label-default pull-right" style="margin:5px;"><%= s.address %></span>
                 
              </li>

            </div>
                                <% end %>

<% end %>


    		  </div>
    	</div>
    </div>

    
	

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/application/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="assets/img/favicon.png">
    
    <link rel="stylesheet" href="assets/css/font-awesome.min.css">


    <title>BloodSeeker</title>

    <!-- Bootstrap core CSS -->
    <link href="assets/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="assets/css/main.css" rel="stylesheet">

    <!-- Fonts from Google Fonts -->
	<link href='http://fonts.googleapis.com/css?family=Lato:300,400,900' rel='stylesheet' type='text/css'>
    
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Fixed navbar 
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><b>BloodSeeker</b></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Already a member?</a></li>
          </ul>
        </div><.nav-collapse -->
      </div>
    </div>

	<div id="headerwrap">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<h1>DonateBlood<br/>
					Feels really good.</h1>
					
					<a href="/auth/facebook"><button type="submit" class="btn btn-social btn-fb" > Sign in with Facebook  </button></a>
					
				</div><!-- /col-lg-6 -->
				<div class="col-lg-6">
					<img class="img-responsive" src="assets/img/real-red-blood-drop.svg" alt="">
				</div><!-- /col-lg-6 -->
				
			</div><!-- /row -->
		</div><!-- /container -->
	</div><!-- /headerwrap -->
	
	
	<div class="container">
		<div class="row mt centered">
			<div class="col-lg-6 col-lg-offset-3">
				<h1>Contribute to the Cause<br/></h1>
				<h3>'ITS BETTER TO DONATE THAN ACCUMULATE</h3>
			</div>
		</div><!-- /row -->
		
		<div class="row mt centered">
			<div class="col-lg-4">
				<i class="fa fa-users fa-5x"></i> 
				<h4>Know Your Match</h4>
				<p>Find out the closest match
				during emergencies</p>
			</div><!--/col-lg-4 -->

			<div class="col-lg-4">
				<i class="fa fa-tint fa-5x"></i>
				<h4>Become A Donor</h4>
				<p>Contribute to the cause
				and save more lives</p>

			</div><!--/col-lg-4 -->

			<div class="col-lg-4">
				<i class="fa fa-trophy fa-5x"></i>
				<h4>Top The Leaderboard</h4>
				<p>Earn points and badges
				and redeem at your nearest outlet</p>

			</div><!--/col-lg-4 -->
		</div><!-- /row -->
	</div><!-- /container -->
	
<hr>
	
	
	

	<div class="container">
		<div class="row mt centered">
			<div class="col-lg-6 col-lg-offset-3">
				<h1>Team</h1>
			</div>
		</div><!-- /row -->
		
		<div class="row mt centered">
			<div class="col-lg-4">
				<img class="img-thumbnail" src="assets/img/pic1.jpg" width="140" height="140" alt="">
				<h4>Ankur Dohare</h4>
				<p>IIIT-Delhi 3rd Year Undergrad, works on UI</p>
				<p><a href="https://www.facebook.com/dre.ankur"><i class="fa fa-facebook-square fa-4x"></i></a><a href="https://twitter.com/dreankur"> <i class="fa fa-twitter-square fa-4x"></i></a></p>
			</div><!--/col-lg-4 -->

			<div class="col-lg-4">
				<img class="img-thumbnail" src="assets/img/pic2.jpg" width="140" height="140" alt="">
				<h4>Magus Verma</h4>
				<p>IIIT-Delhi, 2nd Year Undergrad, loves programming and algorithms</p>
				<p><a href="https://www.facebook.com/magus.verma"><i class="fa fa-facebook-square fa-4x"></i></a></p>
			</div><!--/col-lg-4 -->

			<div class="col-lg-4">
				<img class="img-thumbnail" src="assets/img/pic3.jpg" width="140" height="140" alt="">
				<h4>Kshitij Jain</h4>
				<p>IIIT-Delhi, 3rd Year Undergrad, loves algorithms</p>
				<p><a href="https://www.facebook.com/kshitij.jain.92"><i class="fa fa-facebook-square fa-4x"></i> </a></p>
			</div><!--/col-lg-4 -->
		</div><!-- /row -->
	</div><!-- /container -->
	
	
	

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
  </body>
</html>